CREATE TABLE "Reservations" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"BuildingId"	INTEGER NOT NULL,
	"StoreyId"	INTEGER NOT NULL,
	"RoomId"	INTEGER NOT NULL,
	"DeskId"	INTEGER NOT NULL,
	"UserId"	INTEGER NOT NULL,
	"ReservedAt"	TEXT NOT NULL,
	"TimeStamp"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT),
	FOREIGN KEY("UserId") REFERENCES "Users"("Id"),
	FOREIGN KEY("DeskId") REFERENCES "Desks"("Id"),
	FOREIGN KEY("RoomId") REFERENCES "Rooms"("Id"),
	FOREIGN KEY("StoreyId") REFERENCES "Storeys"("Id"),
	FOREIGN KEY("BuildingId") REFERENCES "Buildings"("Id")
);