CREATE TABLE "Users" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Surname"	TEXT NOT NULL,
	"Username"	TEXT NOT NULL UNIQUE,
	"Password"	TEXT NOT NULL,
	"IsAdmin"	INTEGER NOT NULL,
	"IsTemp"	INTEGER NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);